import type { Metadata } from "next";
import { Suravaram, Open_Sans } from 'next/font/google';
import './globals.css'; import "./globals.css";

const suravaram = Suravaram({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-nirmala',
});

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '600'],
  variable: '--font-open-sans',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${suravaram.variable} ${openSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
